// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SampleMvcApp.Data;

#nullable disable

namespace SampleMvcApp.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20231026212601_BugFix")]
    partial class BugFix
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SampleMvcApp.Data.Entities.Natjecanje", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BodoviPobjeda")
                        .HasColumnType("integer");

                    b.Property<int>("BodoviPoraz")
                        .HasColumnType("integer");

                    b.Property<int>("BodoviRemi")
                        .HasColumnType("integer");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PublicUrl")
                        .HasColumnType("text");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Natjecanje", (string)null);
                });

            modelBuilder.Entity("SampleMvcApp.Data.Entities.Natjecatelj", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BrojBodova")
                        .HasColumnType("integer");

                    b.Property<int>("BrojOdigranihKola")
                        .HasColumnType("integer");

                    b.Property<int>("NatjecanjeId")
                        .HasColumnType("integer");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Razlika")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("NatjecanjeId");

                    b.ToTable("Natjecatelj", (string)null);
                });

            modelBuilder.Entity("SampleMvcApp.Data.Entities.Rezultat", b =>
                {
                    b.Property<int>("IdDomacin")
                        .HasColumnType("integer");

                    b.Property<int>("IdGost")
                        .HasColumnType("integer");

                    b.Property<int>("Ishod")
                        .HasColumnType("integer");

                    b.Property<int>("Kolo")
                        .HasColumnType("integer");

                    b.Property<string>("Vrijednost")
                        .HasColumnType("text");

                    b.HasKey("IdDomacin", "IdGost");

                    b.HasIndex("IdGost");

                    b.ToTable("Rezultat", (string)null);
                });

            modelBuilder.Entity("SampleMvcApp.Data.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("UserIdentifier")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserIdentifier")
                        .IsUnique();

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("SampleMvcApp.Data.Entities.Natjecanje", b =>
                {
                    b.HasOne("SampleMvcApp.Data.Entities.User", "User")
                        .WithMany("Natjecanja")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("User");
                });

            modelBuilder.Entity("SampleMvcApp.Data.Entities.Natjecatelj", b =>
                {
                    b.HasOne("SampleMvcApp.Data.Entities.Natjecanje", "Natjecanje")
                        .WithMany("Natjecatelji")
                        .HasForeignKey("NatjecanjeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Natjecanje");
                });

            modelBuilder.Entity("SampleMvcApp.Data.Entities.Rezultat", b =>
                {
                    b.HasOne("SampleMvcApp.Data.Entities.Natjecatelj", "Domacin")
                        .WithMany("DomaćiRezultati")
                        .HasForeignKey("IdDomacin")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SampleMvcApp.Data.Entities.Natjecatelj", "Gost")
                        .WithMany("GostujućiRezultati")
                        .HasForeignKey("IdGost")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Domacin");

                    b.Navigation("Gost");
                });

            modelBuilder.Entity("SampleMvcApp.Data.Entities.Natjecanje", b =>
                {
                    b.Navigation("Natjecatelji");
                });

            modelBuilder.Entity("SampleMvcApp.Data.Entities.Natjecatelj", b =>
                {
                    b.Navigation("DomaćiRezultati");

                    b.Navigation("GostujućiRezultati");
                });

            modelBuilder.Entity("SampleMvcApp.Data.Entities.User", b =>
                {
                    b.Navigation("Natjecanja");
                });
#pragma warning restore 612, 618
        }
    }
}
